# Generated by Django 4.2.5 on 2023-09-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
